# -*- coding: utf-8 -*-
"""
Created on Wed Jan  1 22:09:51 2020

@author: z.chen7
"""

# 389. Find the Difference

"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""
import collections


class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        counter = collections.Counter(s)
        for c in t:
            if not counter[c]:
                return c
            counter[c] -= 1


class Solution2:
    def findTheDifference(self, s: str, t: str) -> str:
        from collections import Counter
        counter = Counter(t)

        for c in s:
            counter[c] -= 1

        for key, value in counter.items():
            if value > 0:
                return key
